### ISSUE TITLE
Cyrillic "й" is removed from strings

### ISSUE THREAD

**Issue by dmbaturin** [thangngoc89/ocaml-slug#6]
The cyrillic letter "й" is pronounced like "y" in "young". In Russian and Ukrainian, it's never silent, so it shouldn't be removed. However, it _is_ removed!

```
utop # Slug.slugify "мой первый пост" ;; (* "my first post", expected slug: "moy-pervy-post" *)
- : string = "mo-pervy-post"

utop # Slug.slugify "йодистый калий" ;; (* "sodium iodide", expected slug: "yodisty-kaliy" *)
- : string = "odisty-kali"

utop # Slug.slugify "ййй" ;; 
- : string = ""
```

The character maps seem correct, so it's probably some subtle logic issue, I don't see if offhand.

**Comment by thangngoc89** [comment]
Thank you for reporting. This is definitely a bug. 

The [default char](https://github.com/thangngoc89/ocaml-slug/blob/e4d8f79648c202977e46524410d5b55d6c0c6760/data/charmap.json#L303) map converts "й" to "j"

and the Ukranian (uk) charmap [convert "й" to "y"](https://github.com/thangngoc89/ocaml-slug/blob/e4d8f79648c202977e46524410d5b55d6c0c6760/data/locales.json#L64)

I can't immediately know where does the error come from

**Comment by thangngoc89** [comment]
This is "fixed" in https://github.com/thangngoc89/ocaml-slug/commit/f47b60ab2479a07cdec6228704aad1801321be73 . 

So it turns out that `node-slugify` uses `NFC` and provide a charmap for every characters possible. 

Though the commit mentioned above converts the "й" to "y" character.

Your example doesn't work very well "йодистый калий" converts to "yodystyy-kalyy" instead of "yodisty-kaliy".
But this is consistent with `node-slugify` behavior. You can provide custom map to convert this into your desired characters.
